parameters:
    fiendish.class: "DavidMikeSimon\FiendishBundle\DependencyInjection\DavidMikeSimonFiendishExtension"
    fiendish.group.class: "DavidMikeSimon\FiendishBundle\Supervisor\Group"

services:
    fiendish:
        class: "%fiendish.class%"
