parameters:
    david_mike_simon_fiendish.class: "DavidMikeSimon\FiendishBundle\DependencyInjection\DavidMikeSimonFiendishExtension"
    david_mike_simon_fiendish.group.class: "DavidMikeSimon\FiendishBundle\Supervisor\Group"

services:
    david_mike_simon_fiendish:
        class: "%david_mike_simon_fiendish.class%"
