parameters:
    fiendish.class: "AC\FiendishBundle\DependencyInjection\ACFiendishExtension"
    fiendish.group.class: "AC\FiendishBundle\Supervisor\Group"

services:
    fiendish:
        class: "%fiendish.class%"
